groupass1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls')),
    path("transaction/",include("transaction.urls"), name="transaction"),
    path("review/",include("review.urls"), name="review"),
    path('coupon/', include('coupon.urls'), name='coupon'),

]

item/urls.py
from django.urls import path, include
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:index>/', views.dynamicdet, name="dynamicdet")
]

transaction/urls.py
from django.urls import path
from . import views

app_name = "transaction"

urlpatterns = [
    path("history/",views.HistoryView, name="history"),
    path("checkout/",views.checkout, name="checkout"),
    path("add_transaction/",views.add_transaction, name="add_transaction")
]

transaction/models.py
from django.db import models
from item.models import Item
from coupon.models import Coupon

class Transaction(models.Model):
    @property
    def get_transaction(self):
        try:
            return self.item.price_item * (100 - self.coupon.percentage) // 100
        except:
            return self.item.price_item 

    buyer_name = models.TextField(max_length=50)
    item = models.ForeignKey(Item,on_delete=models.PROTECT)
    total_transaction = get_transaction
    coupon = models.ForeignKey(Coupon,on_delete=models.PROTECT,null=True, blank=True) 
    buy_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {} @ {}".format(self.buyer_name, self.item, self.buy_date)

    
        

    

transaction/views.py
from django.shortcuts import render, redirect
from .models import Transaction
from item.models import Item
from coupon.models import Coupon
from django.utils import timezone

def HistoryView(request):
    context = {
        "transaction_list" : Transaction.objects.all().order_by('-buy_date'),
        'nav': [
            ['/', 'Home'],
            ['transaction/history', 'History'],

        ],

    }
    return render(request, "history.html", context)

def checkout(request):
    if request.method == "POST":
        
        name_item = request.POST["name_item"]
        price_item = request.POST["price_item"]
        stock_item = request.POST["stock_item"]
        desc_item = request.POST["desc_item"]
        
        try:
            name_coupon = request.POST["name_coupon"] if request.POST["name_coupon"] else ""
            percentage_coupon = request.POST["percentage_coupon"] if request.POST["percentage_coupon"] else 0
            coupon_list = Coupon.objects.filter(name__icontains = name_coupon)
            coupon_list = coupon_list.filter(percentage__gte = percentage_coupon)
            coupon_list = coupon_list.filter(expired__gte = timezone.now(), min_price__lte = price_item) 
        except:
            coupon_list = Coupon.objects.filter(expired__gte = timezone.now(), min_price__lte = price_item)[:10]
            name_coupon = ""
            percentage_coupon = ""

        item_bought = Item.objects.get(
            name_item = name_item,
            price_item = price_item,
            stock_item = stock_item,
            desc_item = desc_item
        )

        try:
            coupon_chosen = request.POST["coupon_chosen"].split("---")
            name_coupon_chosen = coupon_chosen[0]
            percentage_coupon_chosen = coupon_chosen[1]
            after_discount = int(item_bought.price_item * (100-float(percentage_coupon_chosen)) / 100)
        except:
            name_coupon_chosen = ""
            percentage_coupon_chosen = ""
            after_discount = None

        context = {
            "item_bought" : item_bought,
            "coupon_list" : coupon_list,
            "name_coupon" : name_coupon,
            "percentage_coupon" : percentage_coupon,
            "name_coupon_chosen" : name_coupon_chosen,
            "percentage_coupon_chosen" : percentage_coupon_chosen,
            "after_discount" : after_discount,
            'nav': [
            ['/', 'Home'],
            ['transaction/history', 'History'],

        ],

        }

        return render(request, "checkout.html", context)
    else:
        return redirect("item:index")

def add_transaction(request):
    if request.method == "POST":

        name_item = request.POST["name_item"]
        price_item = request.POST["price_item"]
        stock_item = request.POST["stock_item"]
        desc_item = request.POST["desc_item"]

        buyer_name = request.POST["first_name"] + " " + request.POST["last_name"]

        item_bought = Item.objects.get(
            name_item = name_item,
            price_item = price_item,
            stock_item = stock_item,
            desc_item = desc_item
        )

        try:
            name_coupon_chosen = request.POST["coupon_chosen_name"]
            percentage_coupon_chosen = request.POST["coupon_chosen_percentage"]
            coupon_chosen = Coupon.objects.get(name=name_coupon_chosen, percentage = percentage_coupon_chosen)
        except:
            coupon_chosen = None

        new_transaction = Transaction.objects.create(
            buyer_name = buyer_name,
            item = item_bought,
            coupon = coupon_chosen
        ).save()
        
    
        item_bought.stock_item -= 1 
        item_bought.save()

    return redirect("item:index")

transaction/templates/checkout.html
{% extends 'base.html' %} {% block content %}
<br><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<form action="{% url 'transaction:add_transaction' %}" method="POST">

    {% csrf_token %}
    <input type="hidden" value="{{item_bought.name_item}}" name="name_item">
    <input type="hidden" value="{{item_bought.price_item}}" name="price_item">
    <input type="hidden" value="{{item_bought.stock_item}}" name="stock_item">
    <input type="hidden" value="{{item_bought.desc_item}}" name="desc_item">

    <input type="hidden" value="{{name_coupon_chosen}}" name="coupon_chosen_name">
    <input type="hidden" value="{{percentage_coupon_chosen}}" name="coupon_chosen_percentage">

    <h4>First Name</h4>
    <input type="text" placeholder="First Name" name="first_name" required>
    <h4>Last Name</h4>
    <input type="text" placeholder="Last Name" name="last_name" required>
    <h4>Item Bought: {{item_bought.name_item}}</h4>


    {% if after_discount != None %}
    <h3>Total:</h3>
    <h4>Rp. {{after_discount}}</h4>
    {% else %}
    <h3>Total:</h3>
    <h4>Rp. {{item_bought.price_item}}</h4>
    {% endif %}
    <input type="submit" value="Checkout">
</form>

<form action="{% url 'transaction:checkout' %}" method="POST" class="d-flex justify-content-center align-item-center flex-column">
    {% csrf_token %}

    <input type="hidden" value="{{item_bought.name_item}}" name="name_item">
    <input type="hidden" value="{{item_bought.price_item}}" name="price_item">
    <input type="hidden" value="{{item_bought.stock_item}}" name="stock_item">
    <input type="hidden" value="{{item_bought.desc_item}}" name="desc_item">

    <h4>Coupon Name</h4>
    <input type="text" placeholder="Coupon Name" name="name_coupon">
    <input type="submit" value="Find Coupon"> {% if name_coupon_chosen %}
    <p>You choose "{{name_coupon_chosen}}"</p>
    <h4>Discount {{percentage_coupon_chosen}}%</h4>
    {% endif %} {% if name_coupon %}
    <p>Search for: {{name_coupon}}</p>
    {% endif %} {% if percentage_coupon %}
    <p>Min Percentage : {{percentage_coupon}}%</p>
    {% endif %}


    <p>Coupon Available:</p>
    <div>
        {% for coupon in coupon_list %}
        <div>
            <button type="submit" value="{{coupon.name}}" name="coupon_chosen">
                        <p>{{coupon.name}}</p>
                    </button>
        </div>
        {% endfor %}
    </div>

</form>


</div>
</div>
</div>
</div>

{% endblock %}

transaction/templates/history.html
{% extends 'base.html' %} {% block content %} {% for transaction in transaction_list %}
<h1 class="m-0 p-0">{{transaction.name_buyer}}</h1>
<p class="m-0 p-0">Item: {{transaction.item.name_item}}</p>
<p class="m-0 p-0">{{transaction.buy_date|date:"Y-m-d / G:i"}}</p>
{% if transaction.coupon != None %} Coupon: {{transaction.coupon.name}} ({{transaction.coupon.percentage}}% off) {% else %} No coupon used {% endif %}
</p>
<h2 class="m-0 p-0">Rp. {{transaction.total_transaction}},00</h2>
{% endfor %} {% endblock %}