groupass1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls')),
    path("transaction/",include("transaction.urls"), name="transaction"),
    path("review/",include("review.urls"), name="review"),
    path('coupon/', include('coupon.urls'), name='coupon'),

]

item/urls.py
from django.urls import path, include
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:index>/', views.dynamicdet, name="dynamicdet")
]

item/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=15)
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    objects = models.Manager()
    def __str__(self):
        return self.name
        

class Item(models.Model):
    name_item = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    stock_item = models.PositiveSmallIntegerField(default=0)
    price_item = models.IntegerField()
    desc_item = models.TextField(max_length=250)

    def __str__(self):
        return f'{self.name_item}'

item/forms.py
from django import forms
# from django.utils.timezone import now
from .models import Item

class SearchForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name_item','category']
        labels ={'name_item': 'Looking for something?' }

item/views.py
from django.shortcuts import render
from .models import Item
from .forms import SearchForm
from django.db.models import Q
from review.forms import ReviewForm

# Create your views here.
def index(request):
    all_item = Item.objects.all()
    context={
        'all_item':all_item,
        'form': SearchForm(),
        'nav': [
            ['/', 'Home'],
            ['transaction/history', 'History'],

        ],
    }
    # form = SearchForm()
    if request.method == 'POST':
        query = request.POST['name_item']
        all_item_name = all_item.filter(name_item__icontains=query)
        all_item_category = all_item.filter(category__name__icontains=query)
        context['all_item'] = all_item_name | all_item_category
        return render(request, 'landing.html', context)
    return render(request, "landing.html",context)

def dynamicdet(request, index):
    dynamicdet_item = Item.objects.get(pk=index)
    context={
            "dynamicdet_item" : dynamicdet_item,        
            'nav': [
            ['/', 'Home'],
            ['transaction/history', 'History'],

        ],
    }
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.item = dynamicdet_item
            review.save()

    return render(request, "item.html", context)

item/templates/snippets/navbar.html
{% load static %}

<header>
    <nav class="Navbar" style="mix-blend-mode: difference;">
        <h1><a href="/"> Waroeng</a></h1>
        <div class="flex-ccc">
            <form action="{% url 'item:index' %}" method="POST">
                {% csrf_token %}
                <input class="form-control mr-sm-2 w-50" type="search" placeholder="Cari Barang?" aria-label="Search" name="name_item">
                <input type="submit" class="invisible-button" value="Cari">
            </form>
        </div>

        <ul class="NavbarPages">

            <li>
                {% for link,name in nav%}
                <a href="{{link}}">{{name}}</a> {% endfor %}
            </li>

        </ul>

    </nav>
</header>