groupass1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls')),
    path("transaction/",include("transaction.urls"), name="transaction"),
    path("review/",include("review.urls"), name="review"),
    path('coupon/', include('coupon.urls'), name='coupon'),

]

item/urls.py
from django.urls import path, include
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:index>/', views.dynamicdet, name="dynamicdet")
]

transaction/urls.py
from django.urls import path
from . import views

app_name = "transaction"

urlpatterns = [
    path("history/",views.HistoryView, name="history"),
    path("checkout/",views.checkout, name="checkout"),
    path("add_transaction/",views.add_transaction, name="add_transaction")
]

item/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=15)
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    objects = models.Manager()
    def __str__(self):
        return self.name
        

class Item(models.Model):
    name_item = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    stock_item = models.PositiveSmallIntegerField(default=0)
    price_item = models.IntegerField()
    desc_item = models.TextField(max_length=250)

    def __str__(self):
        return f'{self.name_item}'

review/models.py
from django.db import models
from item.models import Item

# Create your models here.
class Review(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, default=None)
    reviewer_name = models.CharField(max_length=250)
    review = models.CharField(max_length=1000)
    star = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.reviewer_name

item/forms.py
from django import forms
# from django.utils.timezone import now
from .models import Item

class SearchForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name_item','category']
        labels ={'name_item': 'Looking for something?' }

item/views.py
from django.shortcuts import render
from .models import Item
from .forms import SearchForm
from django.db.models import Q
from review.forms import ReviewForm

# Create your views here.
def index(request):
    all_item = Item.objects.all()
    context={
        'all_item':all_item,
        'form': SearchForm(),
        'nav': [
            ['/', 'Home'],
            ['transaction/history', 'History'],

        ],
    }
    # form = SearchForm()
    if request.method == 'POST':
        query = request.POST['name_item']
        all_item_name = all_item.filter(name_item__icontains=query)
        all_item_category = all_item.filter(category__name__icontains=query)
        context['all_item'] = all_item_name | all_item_category
        return render(request, 'landing.html', context)
    return render(request, "landing.html",context)

def dynamicdet(request, index):
    dynamicdet_item = Item.objects.get(pk=index)
    context={
            "dynamicdet_item" : dynamicdet_item,        
            'nav': [
            ['/', 'Home'],
            ['transaction/history', 'History'],

        ],
    }
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.item = dynamicdet_item
            review.save()

    return render(request, "item.html", context)

item/templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/navbar.css'%}" type="text/css">

</head>

<body>
    {% include 'snippets/navbar.html' %}
    <section class="container-100p">
        {% block content %} {% endblock %}
    </section>
</body>
<footer class="bg-black ">
    <div class="grid-block-50vh-img flexrow-ccc">
        <h1>Contact</h1>
        <br>
        <a href="/" style="color: rgba(255,255,255,0.5);">Instagram (Soon)</a>
        <br>
        <a href="/" style="color: rgba(255,255,255,0.5);">Tokopedia (Soon)</a>
    </div>
</footer>

</html>

item/templates/item.html
{% extends 'base.html' %} {% block content %} {{ dynamicdet_item.category_item }}
<h4>{{ dynamicdet_item.name_item }}</h4>
<p>Price : Rp. {{ dynamicdet_item.price_item }}</p>
<p>Quantity: {{dynamicdet_item.stock_item}}</p>
<p>Description: {{ dynamicdet_item.desc_item }}</p>
<p>Category: {{ dynamicdet_item.category }}</p>

{% if dynamicdet_item.stock_item > 0 %}
<form action="{% url 'transaction:checkout' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" value="{{ dynamicdet_item.name_item }}" name="name_item">
    <input type="hidden" value="{{ dynamicdet_item.price_item }}" name="price_item">
    <input type="hidden" value="{{ dynamicdet_item.stock_item }}" name="stock_item">
    <input type="hidden" value="{{ dynamicdet_item.desc_item }}" name="desc_item">
    <input type="submit" class="cta-green" value="Checkout">
</form>
{% else %}
<form action="{% url 'transaction:checkout' %}" method="POST">
    {% csrf_token %}
    <input type="submit" class="cta-green" value="No Stock" disabled>
</form>
{% endif %}


<form action="{% url 'item:dynamicdet' dynamicdet_item.id %}" method="POST">
    {% csrf_token %}
    <input type="text" name="reviewer_name" placeholder="Your name">
    <input type="text" name="review" placeholder="Your review">
    <input type="number" name="star" min=1 max=5 placeholder="Stars">
    <input type="submit" value="submit review">
</form>
{% for review in dynamicdet_item.review_set.all %}
<h3>{{review.reviewer_name}}</h3>
<p>{{review.star}}</p>
<p>{{review.review}}</p>
{% endfor %} {% endblock %}

item/templates/itemrak.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style(Raka).css' %}">
</head>

<body>
    <div class="index"></div>
    <div class="weblogo">Waroeng</div>
    <div class="group43"></div>
    <div class="rectangle31"></div>
    <div class="whatsapp">Whatsapp</div>
    <div class="instagram">Instagram</div>
    <div class="contactus">Contact us</div>
    <div class="searchbutton"></div>
    <div class="searchpng">
        <img src="">
    </div>
    <div class="description">Description</div>
    <div class="descriptiontext">
        Sistem kamera tunggal (Wide) atau ganda (Wide, Telefoto) Pemutaran video hingga 14 jam Tahan air sampai kedalaman 1 meter hingga selama 30 menit Layar Retina HD 4,7” atau 5,5”
    </div>
    <div class="subtotal">Subtotal : Rp. 6,500,000</div>
    <div class="pesantambahan">Pesan tambahan:</div>
    <div class="browsebutton"></div>
    <div class="browsetext">Browse more</div>
    <div class="checkbutton"></div>
    <div class="checkouttext">CHECK OUT</div>
    <div class="productbox"></div>
    <div class="productname">iPhone 8 Plus 64 GB</div>
    <div class="productphotobox"></div>
    <div class="image">
        <img src="static/images/product.jfif">
    </div>

</body>

</html>

item/templates/landing.html
 {% extends 'base.html' %} {% block content %} {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Waroeng</title>
</head>


<body>
    <section class="grid-autofit-la bg-white">
        <div class="container-100p bg-white flex-ccc">
            <img src="{% static 'img/Mac/1.jpg'%}" width="auto" height="400em" min-height="300px">
        </div>
        <div class="container-100p bg-red flexrow-ccc">
            <h1 style="font-size: 4em;">Sale</h1>
            <br>
            <h1 style="font-size: 6em;">50%</h1>
        </div>
    </section>

    <section class="grid-autofit-sm bg-smokewhite">
        {% for element in all_item %}
        <div class="block-300 bg-white margin-1em flexrow-ccc">
            <div>
                <img src="{% static 'img/Mac/'%}{{element.id}}.jpg" class="img" width="auto" height="100px">
            </div>
            <div>
                <p>{{element.category}}</p>
                <h3><a href="{{ element.id }}" style="color: black;"> {{ element.name_item }} </a></h3>
                <br>
                <p>Price : Rp. {{ element.price_item }}</p>
                <p>Quantity: {{element.stock_item}}</p>
                <p>Description: {{element.desc_item}}</p>
            </div>
        </div>
        {% endfor %}
    </section>


</body>

</html>
{% endblock %}